// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/btrepl.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_api_btrepl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_btrepl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_api_btrepl_proto_rawDescGZIP(), []int{0}
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_api_btrepl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_btrepl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_api_btrepl_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RunResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_btrepl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_btrepl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_btrepl_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimerActive   bool                   `protobuf:"varint,1,opt,name=timer_active,json=timerActive,proto3" json:"timer_active,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Slaves        []string               `protobuf:"bytes,3,rep,name=slaves,proto3" json:"slaves,omitempty"`
	Subvolumes    []*SubvolStatus        `protobuf:"bytes,4,rep,name=subvolumes,proto3" json:"subvolumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_btrepl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_btrepl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_btrepl_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetTimerActive() bool {
	if x != nil {
		return x.TimerActive
	}
	return false
}

func (x *StatusResponse) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *StatusResponse) GetSlaves() []string {
	if x != nil {
		return x.Slaves
	}
	return nil
}

func (x *StatusResponse) GetSubvolumes() []*SubvolStatus {
	if x != nil {
		return x.Subvolumes
	}
	return nil
}

type SubvolStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SnapshotCount  int32                  `protobuf:"varint,2,opt,name=snapshot_count,json=snapshotCount,proto3" json:"snapshot_count,omitempty"`
	LatestSnapshot string                 `protobuf:"bytes,3,opt,name=latest_snapshot,json=latestSnapshot,proto3" json:"latest_snapshot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubvolStatus) Reset() {
	*x = SubvolStatus{}
	mi := &file_api_btrepl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubvolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubvolStatus) ProtoMessage() {}

func (x *SubvolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_btrepl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubvolStatus.ProtoReflect.Descriptor instead.
func (*SubvolStatus) Descriptor() ([]byte, []int) {
	return file_api_btrepl_proto_rawDescGZIP(), []int{4}
}

func (x *SubvolStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubvolStatus) GetSnapshotCount() int32 {
	if x != nil {
		return x.SnapshotCount
	}
	return 0
}

func (x *SubvolStatus) GetLatestSnapshot() string {
	if x != nil {
		return x.LatestSnapshot
	}
	return ""
}

type SlaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlaveRequest) Reset() {
	*x = SlaveRequest{}
	mi := &file_api_btrepl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveRequest) ProtoMessage() {}

func (x *SlaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_btrepl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveRequest.ProtoReflect.Descriptor instead.
func (*SlaveRequest) Descriptor() ([]byte, []int) {
	return file_api_btrepl_proto_rawDescGZIP(), []int{5}
}

func (x *SlaveRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type SlaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlaveResponse) Reset() {
	*x = SlaveResponse{}
	mi := &file_api_btrepl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveResponse) ProtoMessage() {}

func (x *SlaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_btrepl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveResponse.ProtoReflect.Descriptor instead.
func (*SlaveResponse) Descriptor() ([]byte, []int) {
	return file_api_btrepl_proto_rawDescGZIP(), []int{6}
}

func (x *SlaveResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SlaveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WatchLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchLogsRequest) Reset() {
	*x = WatchLogsRequest{}
	mi := &file_api_btrepl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchLogsRequest) ProtoMessage() {}

func (x *WatchLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_btrepl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchLogsRequest.ProtoReflect.Descriptor instead.
func (*WatchLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_btrepl_proto_rawDescGZIP(), []int{7}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,4,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_btrepl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_btrepl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_btrepl_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *LogEntry) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

var File_api_btrepl_proto protoreflect.FileDescriptor

const file_api_btrepl_proto_rawDesc = "" +
	"\n" +
	"\x10api/btrepl.proto\x12\tbtrepl.v1\"\f\n" +
	"\n" +
	"RunRequest\"3\n" +
	"\vRunResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0f\n" +
	"\rStatusRequest\"\xa0\x01\n" +
	"\x0eStatusResponse\x12!\n" +
	"\ftimer_active\x18\x01 \x01(\bR\vtimerActive\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12\x16\n" +
	"\x06slaves\x18\x03 \x03(\tR\x06slaves\x127\n" +
	"\n" +
	"subvolumes\x18\x04 \x03(\v2\x17.btrepl.v1.SubvolStatusR\n" +
	"subvolumes\"r\n" +
	"\fSubvolStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0esnapshot_count\x18\x02 \x01(\x05R\rsnapshotCount\x12'\n" +
	"\x0flatest_snapshot\x18\x03 \x01(\tR\x0elatestSnapshot\"\x1e\n" +
	"\fSlaveRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"5\n" +
	"\rSlaveResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x12\n" +
	"\x10WatchLogsRequest\"\xbe\x01\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x124\n" +
	"\x05attrs\x18\x04 \x03(\v2\x1e.btrepl.v1.LogEntry.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xbc\x02\n" +
	"\x06Btrepl\x124\n" +
	"\x03Run\x12\x15.btrepl.v1.RunRequest\x1a\x16.btrepl.v1.RunResponse\x12=\n" +
	"\x06Status\x12\x18.btrepl.v1.StatusRequest\x1a\x19.btrepl.v1.StatusResponse\x12=\n" +
	"\bAddSlave\x12\x17.btrepl.v1.SlaveRequest\x1a\x18.btrepl.v1.SlaveResponse\x12=\n" +
	"\bDelSlave\x12\x17.btrepl.v1.SlaveRequest\x1a\x18.btrepl.v1.SlaveResponse\x12?\n" +
	"\tWatchLogs\x12\x1b.btrepl.v1.WatchLogsRequest\x1a\x13.btrepl.v1.LogEntry0\x01B#Z!github.com/eleutherius/btrepl/apib\x06proto3"

var (
	file_api_btrepl_proto_rawDescOnce sync.Once
	file_api_btrepl_proto_rawDescData []byte
)

func file_api_btrepl_proto_rawDescGZIP() []byte {
	file_api_btrepl_proto_rawDescOnce.Do(func() {
		file_api_btrepl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_btrepl_proto_rawDesc), len(file_api_btrepl_proto_rawDesc)))
	})
	return file_api_btrepl_proto_rawDescData
}

var file_api_btrepl_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_btrepl_proto_goTypes = []any{
	(*RunRequest)(nil),       // 0: btrepl.v1.RunRequest
	(*RunResponse)(nil),      // 1: btrepl.v1.RunResponse
	(*StatusRequest)(nil),    // 2: btrepl.v1.StatusRequest
	(*StatusResponse)(nil),   // 3: btrepl.v1.StatusResponse
	(*SubvolStatus)(nil),     // 4: btrepl.v1.SubvolStatus
	(*SlaveRequest)(nil),     // 5: btrepl.v1.SlaveRequest
	(*SlaveResponse)(nil),    // 6: btrepl.v1.SlaveResponse
	(*WatchLogsRequest)(nil), // 7: btrepl.v1.WatchLogsRequest
	(*LogEntry)(nil),         // 8: btrepl.v1.LogEntry
	nil,                      // 9: btrepl.v1.LogEntry.AttrsEntry
}
var file_api_btrepl_proto_depIdxs = []int32{
	4, // 0: btrepl.v1.StatusResponse.subvolumes:type_name -> btrepl.v1.SubvolStatus
	9, // 1: btrepl.v1.LogEntry.attrs:type_name -> btrepl.v1.LogEntry.AttrsEntry
	0, // 2: btrepl.v1.Btrepl.Run:input_type -> btrepl.v1.RunRequest
	2, // 3: btrepl.v1.Btrepl.Status:input_type -> btrepl.v1.StatusRequest
	5, // 4: btrepl.v1.Btrepl.AddSlave:input_type -> btrepl.v1.SlaveRequest
	5, // 5: btrepl.v1.Btrepl.DelSlave:input_type -> btrepl.v1.SlaveRequest
	7, // 6: btrepl.v1.Btrepl.WatchLogs:input_type -> btrepl.v1.WatchLogsRequest
	1, // 7: btrepl.v1.Btrepl.Run:output_type -> btrepl.v1.RunResponse
	3, // 8: btrepl.v1.Btrepl.Status:output_type -> btrepl.v1.StatusResponse
	6, // 9: btrepl.v1.Btrepl.AddSlave:output_type -> btrepl.v1.SlaveResponse
	6, // 10: btrepl.v1.Btrepl.DelSlave:output_type -> btrepl.v1.SlaveResponse
	8, // 11: btrepl.v1.Btrepl.WatchLogs:output_type -> btrepl.v1.LogEntry
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_btrepl_proto_init() }
func file_api_btrepl_proto_init() {
	if File_api_btrepl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_btrepl_proto_rawDesc), len(file_api_btrepl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_btrepl_proto_goTypes,
		DependencyIndexes: file_api_btrepl_proto_depIdxs,
		MessageInfos:      file_api_btrepl_proto_msgTypes,
	}.Build()
	File_api_btrepl_proto = out.File
	file_api_btrepl_proto_goTypes = nil
	file_api_btrepl_proto_depIdxs = nil
}
