// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/btrepl.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Btrepl_Run_FullMethodName       = "/btrepl.v1.Btrepl/Run"
	Btrepl_Status_FullMethodName    = "/btrepl.v1.Btrepl/Status"
	Btrepl_AddSlave_FullMethodName  = "/btrepl.v1.Btrepl/AddSlave"
	Btrepl_DelSlave_FullMethodName  = "/btrepl.v1.Btrepl/DelSlave"
	Btrepl_WatchLogs_FullMethodName = "/btrepl.v1.Btrepl/WatchLogs"
)

// BtreplClient is the client API for Btrepl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BtreplClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	AddSlave(ctx context.Context, in *SlaveRequest, opts ...grpc.CallOption) (*SlaveResponse, error)
	DelSlave(ctx context.Context, in *SlaveRequest, opts ...grpc.CallOption) (*SlaveResponse, error)
	WatchLogs(ctx context.Context, in *WatchLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
}

type btreplClient struct {
	cc grpc.ClientConnInterface
}

func NewBtreplClient(cc grpc.ClientConnInterface) BtreplClient {
	return &btreplClient{cc}
}

func (c *btreplClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, Btrepl_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btreplClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Btrepl_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btreplClient) AddSlave(ctx context.Context, in *SlaveRequest, opts ...grpc.CallOption) (*SlaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlaveResponse)
	err := c.cc.Invoke(ctx, Btrepl_AddSlave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btreplClient) DelSlave(ctx context.Context, in *SlaveRequest, opts ...grpc.CallOption) (*SlaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlaveResponse)
	err := c.cc.Invoke(ctx, Btrepl_DelSlave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btreplClient) WatchLogs(ctx context.Context, in *WatchLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Btrepl_ServiceDesc.Streams[0], Btrepl_WatchLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Btrepl_WatchLogsClient = grpc.ServerStreamingClient[LogEntry]

// BtreplServer is the server API for Btrepl service.
// All implementations must embed UnimplementedBtreplServer
// for forward compatibility.
type BtreplServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	AddSlave(context.Context, *SlaveRequest) (*SlaveResponse, error)
	DelSlave(context.Context, *SlaveRequest) (*SlaveResponse, error)
	WatchLogs(*WatchLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	mustEmbedUnimplementedBtreplServer()
}

// UnimplementedBtreplServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBtreplServer struct{}

func (UnimplementedBtreplServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedBtreplServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedBtreplServer) AddSlave(context.Context, *SlaveRequest) (*SlaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSlave not implemented")
}
func (UnimplementedBtreplServer) DelSlave(context.Context, *SlaveRequest) (*SlaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelSlave not implemented")
}
func (UnimplementedBtreplServer) WatchLogs(*WatchLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method WatchLogs not implemented")
}
func (UnimplementedBtreplServer) mustEmbedUnimplementedBtreplServer() {}
func (UnimplementedBtreplServer) testEmbeddedByValue()                {}

// UnsafeBtreplServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BtreplServer will
// result in compilation errors.
type UnsafeBtreplServer interface {
	mustEmbedUnimplementedBtreplServer()
}

func RegisterBtreplServer(s grpc.ServiceRegistrar, srv BtreplServer) {
	// If the following call panics, it indicates UnimplementedBtreplServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Btrepl_ServiceDesc, srv)
}

func _Btrepl_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtreplServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Btrepl_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtreplServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Btrepl_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtreplServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Btrepl_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtreplServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Btrepl_AddSlave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtreplServer).AddSlave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Btrepl_AddSlave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtreplServer).AddSlave(ctx, req.(*SlaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Btrepl_DelSlave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtreplServer).DelSlave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Btrepl_DelSlave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtreplServer).DelSlave(ctx, req.(*SlaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Btrepl_WatchLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BtreplServer).WatchLogs(m, &grpc.GenericServerStream[WatchLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Btrepl_WatchLogsServer = grpc.ServerStreamingServer[LogEntry]

// Btrepl_ServiceDesc is the grpc.ServiceDesc for Btrepl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Btrepl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "btrepl.v1.Btrepl",
	HandlerType: (*BtreplServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Btrepl_Run_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Btrepl_Status_Handler,
		},
		{
			MethodName: "AddSlave",
			Handler:    _Btrepl_AddSlave_Handler,
		},
		{
			MethodName: "DelSlave",
			Handler:    _Btrepl_DelSlave_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchLogs",
			Handler:       _Btrepl_WatchLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/btrepl.proto",
}
