# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from btrepl._pb import btrepl_pb2 as btrepl__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in btrepl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BtreplStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_unary(
                '/btrepl.v1.Btrepl/Run',
                request_serializer=btrepl__pb2.RunRequest.SerializeToString,
                response_deserializer=btrepl__pb2.RunResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/btrepl.v1.Btrepl/Status',
                request_serializer=btrepl__pb2.StatusRequest.SerializeToString,
                response_deserializer=btrepl__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.AddSlave = channel.unary_unary(
                '/btrepl.v1.Btrepl/AddSlave',
                request_serializer=btrepl__pb2.SlaveRequest.SerializeToString,
                response_deserializer=btrepl__pb2.SlaveResponse.FromString,
                _registered_method=True)
        self.DelSlave = channel.unary_unary(
                '/btrepl.v1.Btrepl/DelSlave',
                request_serializer=btrepl__pb2.SlaveRequest.SerializeToString,
                response_deserializer=btrepl__pb2.SlaveResponse.FromString,
                _registered_method=True)
        self.WatchLogs = channel.unary_stream(
                '/btrepl.v1.Btrepl/WatchLogs',
                request_serializer=btrepl__pb2.WatchLogsRequest.SerializeToString,
                response_deserializer=btrepl__pb2.LogEntry.FromString,
                _registered_method=True)


class BtreplServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSlave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelSlave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BtreplServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=btrepl__pb2.RunRequest.FromString,
                    response_serializer=btrepl__pb2.RunResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=btrepl__pb2.StatusRequest.FromString,
                    response_serializer=btrepl__pb2.StatusResponse.SerializeToString,
            ),
            'AddSlave': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSlave,
                    request_deserializer=btrepl__pb2.SlaveRequest.FromString,
                    response_serializer=btrepl__pb2.SlaveResponse.SerializeToString,
            ),
            'DelSlave': grpc.unary_unary_rpc_method_handler(
                    servicer.DelSlave,
                    request_deserializer=btrepl__pb2.SlaveRequest.FromString,
                    response_serializer=btrepl__pb2.SlaveResponse.SerializeToString,
            ),
            'WatchLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchLogs,
                    request_deserializer=btrepl__pb2.WatchLogsRequest.FromString,
                    response_serializer=btrepl__pb2.LogEntry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'btrepl.v1.Btrepl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('btrepl.v1.Btrepl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Btrepl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/btrepl.v1.Btrepl/Run',
            btrepl__pb2.RunRequest.SerializeToString,
            btrepl__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/btrepl.v1.Btrepl/Status',
            btrepl__pb2.StatusRequest.SerializeToString,
            btrepl__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSlave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/btrepl.v1.Btrepl/AddSlave',
            btrepl__pb2.SlaveRequest.SerializeToString,
            btrepl__pb2.SlaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DelSlave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/btrepl.v1.Btrepl/DelSlave',
            btrepl__pb2.SlaveRequest.SerializeToString,
            btrepl__pb2.SlaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/btrepl.v1.Btrepl/WatchLogs',
            btrepl__pb2.WatchLogsRequest.SerializeToString,
            btrepl__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
