# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: btrepl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'btrepl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62trepl.proto\x12\tbtrepl.v1\"\x0c\n\nRunRequest\"(\n\x0bRunResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x0f\n\rStatusRequest\"u\n\x0eStatusResponse\x12\x14\n\x0ctimer_active\x18\x01 \x01(\x08\x12\x10\n\x08interval\x18\x02 \x01(\t\x12\x0e\n\x06slaves\x18\x03 \x03(\t\x12+\n\nsubvolumes\x18\x04 \x03(\x0b\x32\x17.btrepl.v1.SubvolStatus\"M\n\x0cSubvolStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0esnapshot_count\x18\x02 \x01(\x05\x12\x17\n\x0flatest_snapshot\x18\x03 \x01(\t\"\x1a\n\x0cSlaveRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"*\n\rSlaveResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x12\n\x10WatchLogsRequest\"\x95\x01\n\x08LogEntry\x12\r\n\x05level\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12-\n\x05\x61ttrs\x18\x04 \x03(\x0b\x32\x1e.btrepl.v1.LogEntry.AttrsEntry\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xbc\x02\n\x06\x42trepl\x12\x34\n\x03Run\x12\x15.btrepl.v1.RunRequest\x1a\x16.btrepl.v1.RunResponse\x12=\n\x06Status\x12\x18.btrepl.v1.StatusRequest\x1a\x19.btrepl.v1.StatusResponse\x12=\n\x08\x41\x64\x64Slave\x12\x17.btrepl.v1.SlaveRequest\x1a\x18.btrepl.v1.SlaveResponse\x12=\n\x08\x44\x65lSlave\x12\x17.btrepl.v1.SlaveRequest\x1a\x18.btrepl.v1.SlaveResponse\x12?\n\tWatchLogs\x12\x1b.btrepl.v1.WatchLogsRequest\x1a\x13.btrepl.v1.LogEntry0\x01\x42#Z!github.com/eleutherius/btrepl/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'btrepl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!github.com/eleutherius/btrepl/api'
  _globals['_LOGENTRY_ATTRSENTRY']._loaded_options = None
  _globals['_LOGENTRY_ATTRSENTRY']._serialized_options = b'8\001'
  _globals['_RUNREQUEST']._serialized_start=27
  _globals['_RUNREQUEST']._serialized_end=39
  _globals['_RUNRESPONSE']._serialized_start=41
  _globals['_RUNRESPONSE']._serialized_end=81
  _globals['_STATUSREQUEST']._serialized_start=83
  _globals['_STATUSREQUEST']._serialized_end=98
  _globals['_STATUSRESPONSE']._serialized_start=100
  _globals['_STATUSRESPONSE']._serialized_end=217
  _globals['_SUBVOLSTATUS']._serialized_start=219
  _globals['_SUBVOLSTATUS']._serialized_end=296
  _globals['_SLAVEREQUEST']._serialized_start=298
  _globals['_SLAVEREQUEST']._serialized_end=324
  _globals['_SLAVERESPONSE']._serialized_start=326
  _globals['_SLAVERESPONSE']._serialized_end=368
  _globals['_WATCHLOGSREQUEST']._serialized_start=370
  _globals['_WATCHLOGSREQUEST']._serialized_end=388
  _globals['_LOGENTRY']._serialized_start=391
  _globals['_LOGENTRY']._serialized_end=540
  _globals['_LOGENTRY_ATTRSENTRY']._serialized_start=496
  _globals['_LOGENTRY_ATTRSENTRY']._serialized_end=540
  _globals['_BTREPL']._serialized_start=543
  _globals['_BTREPL']._serialized_end=859
# @@protoc_insertion_point(module_scope)
